### ISSUE TITLE
generate PNN (based on 1) 문제 

### ISSUE THREAD

**Issue by sunhoi** [stannam/KPNN#12]
source(".\\generate_PNN.r", encoding = "UTF-8")

net <- genPNN(data = data,
              entry = "entry",
              convention = "klat",
              # surface = T,  #(surface is a parameter to be added for surfacing orthographic form)
              unit = "klat",
              deletion = T,
              pajek = F)
을 돌렸더니

Error in detectCores() : could not find function "detectCores"
Called from: makeSOCKcluster(spec, ...)
Browse[1]> 

이런 에러가 나네.

**Comment by stannam** [comment]
코드를 일부 수정했습니다. pull하신 이후에 작동이 되나 확인해주세요^^

**Comment by sunhoi** [comment]
정상 작동함. 왜 오류가 났으며, 무얼 수정하여 정상 작동하는지?

**Comment by stannam** [comment]
detectCores() 라는 함수를 발견하지 못해서 에러가 났습니다. 
음운이웃쌍을 구하려면 동시에 작업을 하는 '병렬처리'를 해야 하는데, detectCores()함수는 병렬처리를 위해서 컴퓨터 CPU의 코어 개수를 파악하는 함수입니다. 
이 함수는 parallel이라는 패키지의 일부라서, parallel 패키지를 다시 불러오는 코드를 맨 처음에 추가했습니다.^^

**Comment by sunhoi** [comment]
OK! Thank you.
