### ISSUE TITLE
pull/push에 대한 것

### ISSUE THREAD

**Issue by sunhoi** [stannam/KPNN#18]
만약 내가 KPNN 프로젝트에 대해 r-studio에서 push를 했으면, 여기에서 pull request는 남성현만 할 수 있는지, 아니면  나도 할 수 있는지 모르겠네. 아무나 할 수 있으면, 동일 파일의 코드가 덮어 써 질 수 도 있을 거 같아서.

**Comment by stannam** [comment]
pull request는, 허락받지 않은 제3자가 "본인의 코드를 봐달라"라고 할때 쓰는 기능입니다.

예를들어서 허락받지 않은 제3자가 KPNN에 관심이 생겨서 기여를 하고 싶어졌다고 가정했을 때,

그 사람은 코드를 다운로드 한 다음, 그 위에다가 발전을 시킬 수 있습니다. 하지만 아무리 그래도 저희가 가지고 있는 "표준" KPNN에는 반영이 되지 않습니다. 다만, "표준 KPNN"에서 파생된 branch (곁다리)를 새로 만들 수 있습니다.

이때, 곁다리를 "표준 KPNN"에 반영해달라고 요청하는 것이 Pull request입니다. 제3자가 pull request를 건다면, 저와 교수님이 해당 코드를 검사한 다음, 기존의 코드와 충돌을 일으키지 않고 기타 문제가 없다면, 그 요청을 받아들여서 "표준 KPNN"을 업데이트할 수 있습니다.

교수님과 저는 push를 통해서 언제나 표준 KPNN을 업데이트 할 수 있으며, 만약 진행을 하다가 문제가 생겨서 예전의 파일로 돌아갈 필요가 있다면, commit (아래 그림 참조) 목록을 보면서 번복(revert)할 수 있습니다.

![image](https://user-images.githubusercontent.com/43150234/60393939-c6b93f80-9b57-11e9-8c17-d65f475cb082.png)
