### ISSUE TITLE
프로세싱 중간중간 결과값을 내놓는 문제 (예를 들면 klattese로 변환된 형태): 지난 번 미팅에서 의논했던 것

### ISSUE THREAD

**Issue by sunhoi** [stannam/KPNN#19]
프로세싱 중간중간 결과값을 내놓는 장치를 마련했으면 하는데... 예를 들면, PNN 형성 전 klattese로 변환된 형태를 결과값으로 얻을 수 있는 장치. (각종 지표값 도출 포함) (이번 수요일에 얘기할 내용)

**Comment by stannam** [comment]
cf. #10

**Comment by stannam** [comment]
사용자 매뉴얼(7-2-2019 판)에 klattese로 변환된 형태 도출하는 방법을 추가하였습니다. (5.2절) 사용자매뉴얼은 메일로 보내드렸습니다.
