### ISSUE TITLE
사이시옷 문제

### ISSUE THREAD

**Issue by stannam** [stannam/KPNN#4]
어중 C 이전의 'ㅅ'은 무조건 사이시옷으로 가정하고 제거할 수 있는 기능 

(preprocessing문제)

**Comment by stannam** [comment]
updateSaisiot still not working.

**Comment by sunhoi** [comment]
사이시옷 코드 해결된거니?

**Comment by stannam** [comment]
네 해결된 것 같습니다^^ pull하신다음 테스트해보시면 될 것 같습니다.

**Comment by sunhoi** [comment]
수정된 코드로 해 보니, user_choice에 뭔가를 넣으면 (예를 들어, "못하"의 경우 "모하")를 넣으면 제대로 되는데, 아무 것도 안 넣으면 그 단어 즉, "못하"에  대해서 NA가 나오네. 그래서 user_choice를 공백으로 안 두면 될 것 같네 (공백으로 두면 원래 단어형이 나오지는 않지만). 근데, 무얼 수정해서 작동이 되는 건지?

**Comment by stannam** [comment]
사이시옷 후보군을 엑셀 등에서 수정한 후 read.csv로 불러왔을 때, 각 행의 값을 character가 아닌 factor 자료형으로 불러오는 것이 문제였습니다. 이것을 고려하여서 무조건 character 형으로 변환하는 코드를 추가했습니다.
NA가 나오는 문제도 쉽게 해결될 것 같습니다^^

**Comment by stannam** [comment]
user_choice를 비워두었을 때 문제 해결했습니다^^
